data<-read.table('household_power_consumption.txt',sep=';',header=TRUE)
data$Date<-as.Date(data$Date,'%d/%m/%Y')
data$Date<-format(data$Date,format='%d-%m-%Y')
data1<-subset(data,Date=="01-02-2007"|Date=='02-02-2007')
x<-paste(data1$Date,data1$Time)
datetime<-strptime(x,'%d-%m-%Y %H:%M:%S')
kilowatt<-as.numeric(as.character(data1$Global_active_power))
par(lab=c(4,5,7))
hist(kilowatt,xlab='Global Active Power (kilowatts)',main='Global Active Power',col='red',xlim=c(0,6),breaks=24)
dev.copy(png,filename='plot1.png',width=480,height=480)
dev.off()