data<-read.table('household_power_consumption.txt',sep=';',header=TRUE)
data$Date<-as.Date(data$Date,'%d/%m/%Y')
data$Date<-format(data$Date,format='%d-%m-%Y')
data1<-subset(data,Date=="01-02-2007"|Date=='02-02-2007')
x<-paste(data1$Date,data1$Time)
datetime<-strptime(x,'%d-%m-%Y %H:%M:%S')
kilowatt<-as.numeric(as.character(data1$Global_active_power))
plot(datetime,kilowatt,ylab='Global Active Power (kilowatts)',xlab='',type='n')
lines(datetime,kilowatt)
dev.copy(png,filename='plot2.png',width=480,height=480)
dev.off()
